Feat: general wrapper
AutoResearch/autora-core pull request #26
Opened 2023-07-09 21:08 UTC by younesStrittmatter

# Description

a general wrapper that accepts arguments to field mappings as arguments

# Type of change
- **feat**: A new feature

2023-07-10 11:00 UTC, benwandrew commented on src/autora/state/wrapper.py
> +        We define an arbitraty function
```suggestion
        We define an arbitrary function
```

2023-07-10 11:03 UTC, benwandrew commented on src/autora/state/wrapper.py
> +        ...                                         theorist,
do we want to include keywords?

```suggestion
        ...                                         f=theorist,
```

2023-07-10 11:04 UTC, benwandrew commented on src/autora/state/wrapper.py
> +        ...                                         {'x':'experiment_data', 'v':'variables'},
```suggestion
        ...                                         input_state_mapping={'x':'experiment_data', 'v':'variables'},
```

2023-07-10 11:04 UTC, benwandrew commented on src/autora/state/wrapper.py
> +        ...                                          'model')
```suggestion
        ...                                          output_field_name='model')
```

2023-07-10 11:11 UTC, benwandrew commented on src/autora/state/wrapper.py
> +        Any parameters not provided by the state can still be provided by to the wrapped function
```suggestion
        Any parameters not provided by the state can still be provided to the wrapped function
```

2023-07-10 11:14 UTC, benwandrew commented on src/autora/state/wrapper.py
> +        ... then it need to be passed.
need this? not quite sure how to read as a continuation of previous sentence (which seems comprehensive)

2023-07-10 13:59 UTC, benwandrew reviewed
this is super cool! i hope John Ousterhout* would like the direction we're moving in ;)

few suggestions and fixed a pre-commit error, but looking very good!

one general question for my own understanding (which may be better for me to address in office hours): i'm confused about the relationship between the decorator/wrapper `wrap_to_use_state` in `delta.py` and this new `wrap_to_use_state_general` in `wrapper.py`. is the latter not ultimately replacing the former?

*reference to author of a book @hollandjg shared a while ago: https://milkov.tech/assets/psd.pdf

2023-07-10 17:58 UTC, hollandjg commented
I like the look of this!

Would it be sensible to split up the wrapper into two – one which does the input name mapping, and one which does the output wrapping? Then we could use the two independently – perhaps your inner function needs to return two values (say `conditions` and `experiment_js_code`) and returns those as a `Result`/`Delta` object, but you still want a mapping. Conversely, perhaps you have a function which uses entirely standard naming for the variables, but you want to wrap the outputs.

2023-07-15 15:54 UTC, musslick requested changes
Looks great; just got a minor comment for a name change.

2023-07-15 15:54 UTC, musslick commented on src/autora/state/wrapper.py
> +def wrap_to_use_state_general(
Could the name be shorted, e.g., ``wrap_to_state``? I imagine people will be using this a lot, so we might want to give it a short name.

2023-08-22 12:39 UTC, hollandjg commented
hey @younesStrittmatter , do you think you could refactor this so that there's a wrapper function which just does the input field-name mapping? We could include that as an option in the `on_state` function from #33, but it needs to be an independent wrapper function first so that we can test it really extensively on its own.

2023-12-01 21:44 UTC, hollandjg commented
I think this is covered by the newest version of the state object – closing this now.

2023-12-01 21:44 UTC, closed without merging