feat: change state to userdict
AutoResearch/autora-core pull request #44
Opened 2023-08-31 23:19 UTC by younesStrittmatter

# Description

Change state into a user dict

- resolves https://github.com/AutoResearch/autora/issues/548

# Type of change
- **feat**: A new feature

- **BREAKING_CHANGE**: Not sure if it breaks existing code, but tests/notebooks in the core worked fine

# Remarks (Optional)
- The old state class is still implemented and State, StandardState are now aliases of the "Dict"-Versions. If we find Problems, we can easily go back to the Dataclass solution
- The advantage of this is, that the fields of the state can now be changed dynamically. For example, one can add fields easily and alter their "delta"-behaviour between cycles

2023-09-01 08:39 UTC, musslick requested changes
This looks great! The only suggestion I have is to add a minimal jupyter notebook under docs/cycle that outlines the new functionality, i.e., how the state can be modified (adding fields, changing delta functions).

2023-09-03 10:23 UTC, musslick approved these changes
Looks great!

2023-09-03 11:40 UTC, merged

2023-09-04 08:18 UTC, hollandjg requested changes
I think this needs a bunch of automated tests before it gets merged — it's such a central part of the core, that we really need confidence it's working!

2023-09-04 08:18 UTC, hollandjg commented on src/autora/state.py
> +class StateDict(UserDict):
I think this class would benefit from a bunch of doctests which demo and check it's full functionality! You could start with the doctests in the StandardState as an example, and then add the new functionality too.